/* ================================================================
   TILES — the chassis

   One tile chassis for every widget: icon slot, label, sub, badge
   corners (kind / service / routing mark / system), trailing action
   zone, touch long-press, span arithmetic and column fitting. The
   per-domain widget adapters (widgets/*.js) fill the slots; nothing
   in here knows what a light or a Sonos is.
   ================================================================ */
/* the ACCENT palette's eight slots (identity-palette V1; the word is
   ACCENT everywhere people see it — round-4 ruling, matching the
   v0.48.3 activity accent) and the additive style vocabulary. A
   slot is a NAME; hues live in the theme (tokens.css
   @identity-palette block). The style axes compose: icon|text ×
   basic|tint|bloom. `identity`/`identity_style` stay as compat
   reads for drafts saved in the first cut. */
/* @identity-slots-begin (generated by tools/gen-identity-palette.mjs) */
const ID_SLOTS = { coral: 1, fern: 1, jade: 1, indigo: 1, violet: 1, orchid: 1, rose: 1, slate: 1, firetv: 1, appletv: 1, googletv: 1, samsung: 1, lg: 1, sony: 1, sonos: 1, netflix: 1, spotify: 1, plex: 1, roku: 1, shield: 1, disney: 1, youtube: 1, prime: 1, peacock: 1, paramount: 1, max: 1, hulu: 1, fubo: 1, espn: 1, britbox: 1, pbs: 1 };
/* @identity-slots-end */
/* round-5 naming ("every style has both text and icon, so these
   style names are not great"): Basic / Tint / Bloom, plus the
   preset TITLE layout (the name leads the cell) composing with the
   same washes. Every earlier spelling stays a synonym. */
const ID_STYLES = {
  basic: null, "icon-basic": null,   /* the silent default, sayable */
  tint: "ids-tint", "icon-tint": "ids-tint",
  bloom: "ids-bloom", "icon-bloom": "ids-bloom",
  title: "ids-text", text: "ids-text",
  "title-tint": "ids-text ids-tint", "text-tint": "ids-text ids-tint",
  "title-bloom": "ids-text ids-pbloom", "text-bloom": "ids-text ids-pbloom",
};
/* "#rrggbb" / "#rgb" → "r, g, b" for rgba(var(--idw), a) */
/* V2 (palette canvas): which ink survives on this badge — dark
   --accent-ink or white, by WCAG contrast. Mirrors the generator's
   pickInk so a custom hex behaves exactly like a baked slot. */
function pickInk(hexColor) {
  const m = /^#([0-9a-fA-F]{6})$/.exec(String(hexColor || ""));
  if (!m) return null;
  const lum = function (r, g, b) {
    const f = function (v) {
      v /= 255;
      return v <= 0.04045 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
    };
    return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
  };
  const n = parseInt(m[1], 16);
  const lb = lum((n >> 16) & 255, (n >> 8) & 255, n & 255);
  const lDark = lum(20, 24, 29);          /* --accent-ink #14181d */
  const rDark = (Math.max(lb, lDark) + 0.05) / (Math.min(lb, lDark) + 0.05);
  const rWhite = (1.05) / (lb + 0.05);
  return rDark >= rWhite ? "var(--accent-ink)" : "#ffffff";
}
function hexTriplet(hx) {
  const m = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(String(hx || "").trim());
  if (!m) return null;
  let h = m[1];
  if (h.length === 3) h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
  return [0, 2, 4].map(i => parseInt(h.slice(i, i + 2), 16)).join(", ");
}
function iconHtml(t, row) {
  let inner;
  if (t.icon_image) {
    /* ARTWORK FALLS BACK TO THE ICON (v0.68.7). Cover art is a REMOTE
       url — a Spotify CDN, a Sonos coordinator, an MA thumbnail. The
       panel is a wall tablet: the internet drops, a favorite is
       re-added under a new id, a coordinator reboots. A broken-image
       glyph where the album art was is the same failure as a blank
       panel, so the declared `icon` stays on the tile as the
       understudy — see the delegated error handler below. */
    const fb = t.icon && t.icon.startsWith("material:") ? t.icon.slice(9) : "";
    inner = `<img src="${t.icon_image}" alt=""` +
      (t.icontain ? ' class="contain"' : "") +
      (fb ? ` data-fbk="${fb}"` : "") + ">";
    /* ART BOX (v0.85.7 — Suresh: "When artwork hasn't arrived the
       library tiles default to squished"): the art-forward browse
       tile sizes its art `height: auto`, which is 0 until the bytes
       land — so a slow CDN collapsed the whole tile to its label.
       Wrap the art in a square reserved via the padding trick (no
       aspect-ratio on the Chromium-61 floor): correct size from the
       first paint, placeholder ground while loading, and the broken-
       image fallback icon centers in the same box. */
    if (t.brw && !row) inner = `<span class="artbox">${inner}</span>`;
  } else if (t.icon && t.icon.startsWith("material:"))
    inner = `<span class="ic material-symbols-outlined">${t.icon.slice(9)}</span>`;
  else if (t.icon && ICON_SET_RE.test(t.icon)) {
    /* ICON SETS (0.87 re-cut, 2026-09-01 — Suresh: "live preview in
       the studio and then mint into the deployed artifacts"): every
       deploy bakes the referenced icons' PATH DATA into the config
       (store.py minting → CONFIG.icon_paths), so a phu:/mdi: icon is
       inline SVG here — currentColor-tinted like a font glyph, zero
       runtime dependency on any pack or file. A hand-dropped SVG in
       www/harmonium/icons/<set>/<name>.svg survives as the fallback
       (mask + probe, exactly the app-logos machinery); a name
       nothing supplies falls to the neutral glyph. */
    const ip = (CONFIG.icon_paths || {})[t.icon];
    if (ip && ip.path) {
      const vb = String(ip.viewBox || "0 0 24 24").replace(/[^0-9 .-]/g, "");
      const d = String(ip.path).replace(/["<>&]/g, "");
      /* INK FIT (round 8 — Suresh: "the phu icons still seem small at
         1 rem. do they have an inheritantly different scale?" — yes:
         every pack pads its grid differently, and brand marks carry
         safe margins, while Material Symbols ink nearly fills its em.
         So the pack's viewBox is replaced with the PATH'S OWN ink
         box, measured once per icon (getBBox after mount), padded to
         the material live-area ratio — every set icon then sits at
         the same optical size as its material sisters). */
      const fvb = FIT_VB[t.icon];
      /* a re-render builds from the cache, so the wide-mark span
         width must be emitted here too, not only in the fit pass */
      let wst = "";
      if (fvb) {
        const q = fvb.split(" ");
        const a = parseFloat(q[2]) / parseFloat(q[3]);
        if (a > 1.01) wst = ` style="width:${a.toFixed(3)}em"`;
      }
      inner = `<span class="ic icsvg"${wst}><svg viewBox="${fvb || vb}"` +
        (fvb ? "" : ` data-fit="${t.icon}"`) + ` aria-hidden="true">` +
        `<path d="${d}" fill="currentColor"/></svg></span>`;
      if (!fvb) queueIconFit();
    } else {
      const url = "/local/harmonium/icons/" +
        t.icon.replace(":", "/") + ".svg";
      inner = IMG_DEAD.has(url)
        ? `<span class="ic">•</span>`
        : `<span class="ic icmask" style="-webkit-mask-image:url('${url}');mask-image:url('${url}')">` +
          `<img class="mprobe" src="${url}" alt=""></span>`;
    }
  }
  else inner = `<span class="ic">${t.icon || "•"}</span>`;
  return row ? `<div class="icwrap">${inner}</div>` : inner;
}
/* one set-icon spelling: set and name are file-name-safe tokens
   (material: is the font and never reaches this test first) */
const ICON_SET_RE = /^[A-Za-z0-9_-]+:[A-Za-z0-9_-]+$/;
/* ink-fitted viewBoxes, measured once per icon ref. The pass runs a
   tick after render (getBBox needs mounted, laid-out SVG); a hidden
   icon measures 0×0 and keeps its data-fit for a later render. Ink is
   padded to ~83% of the box — Material's 20-in-24 live area. */
const FIT_VB = {};
let fitQueued = false;
function queueIconFit() {
  if (fitQueued) return;
  fitQueued = true;
  setTimeout(fitSetIcons, 0);
}
function fitSetIcons() {
  fitQueued = false;
  const svgs = document.querySelectorAll("svg[data-fit]");
  for (let i = 0; i < svgs.length; i++) {
    const sv = svgs[i], ref = sv.getAttribute("data-fit");
    let vb = FIT_VB[ref];
    if (!vb) {
      let b;
      try { b = sv.getBBox(); } catch (e) { continue; }
      if (!b || !b.width || !b.height) continue;
      /* square icons fit by their long side; a WIDE mark (a wordmark
         logo) fits by the geometric mean instead — otherwise
         square-fitting a 3:1 mark leaves a sliver of ink (round 8:
         "in activities, the PHU icon (firetv) is teeny"). The
         viewBox keeps the ink's TRUE aspect and the host span is
         widened to match (width in em), so layout knows the real
         width — a right-anchored Title mark sits flush instead of
         its overflow crowding the tile edge (round 8 tweak: "the
         sonos icon is too tight to the right of the tile"). */
      const side = Math.max(b.height, Math.sqrt(b.width * b.height));
      const pad = side * 0.08;
      const vh = side + pad * 2, vw = Math.max(b.width, side) + pad * 2;
      const cx = b.x + b.width / 2, cy = b.y + b.height / 2;
      vb = (cx - vw / 2).toFixed(2) + " " + (cy - vh / 2).toFixed(2) +
        " " + vw.toFixed(2) + " " + vh.toFixed(2);
      FIT_VB[ref] = vb;
    }
    sv.setAttribute("viewBox", vb);
    sv.removeAttribute("data-fit");
    /* the span's width follows the fitted aspect (1em when square) */
    var p4 = vb.split(" ");
    var asp = parseFloat(p4[2]) / parseFloat(p4[3]);
    if (asp > 1.01) sv.parentNode.style.width = asp.toFixed(3) + "em";
  }
}
/* photo URLs that failed to load this session — consulted by the
   preset widget so a rebuilt tile skips a known-dead image */
const IMG_DEAD = new Set();
/* `error` does not bubble, but it DOES capture — one document-level
   listener covers every tile ever rendered, with no per-image wiring
   and nothing to clean up on re-render. */
document.addEventListener("error", ev => {
  const im = ev.target;
  if (!im || im.tagName !== "IMG" || !im.parentNode) return;
  /* photo preset whose picture died (v0.85.8): shed the .photo dress
     so the tile reverts to its icon square — the icon and label are
     already in the DOM, only hidden by the photo CSS. The URL is
     REMEMBERED (IMG_DEAD): generated tiles (the apps drawer) rebuild
     on every state diff, and without the memory each rebuild would
     re-request the missing file — a 404 per state change on a kiosk.
     A later-fixed file is picked up on the next engine reload. */
  if (im.getAttribute("data-pfb")) {
    IMG_DEAD.add(im.getAttribute("src"));
    const tl = im.closest(".tile");
    if (tl) tl.classList.remove("photo");
    im.parentNode.removeChild(im);
    return;
  }
  /* a SET ICON whose file is missing (0.87 icon sets): the probe img
     inside the masked span errored — fall back to the neutral glyph
     and remember, so rebuilds render the fallback directly */
  if (im.classList.contains("mprobe")) {
    IMG_DEAD.add(im.getAttribute("src"));
    const sp = im.parentNode;
    sp.className = "ic";
    sp.removeAttribute("style");
    sp.textContent = "•";
    return;
  }
  const fbk = im.getAttribute("data-fbk");
  if (!fbk) return;
  const s = document.createElement("span");
  s.className = "ic material-symbols-outlined";
  s.textContent = fbk;
  im.parentNode.replaceChild(s, im);
}, true);

const REF_W = 480;        /* the panel this layout was authored on */
const GRID_PAD = 24;      /* #grid padding, both sides */
const GRID_GAP = 10;      /* --grid-gap default */
const MAX_COLS = 12;      /* a 4K monitor is not an invitation */
function isWide() { return document.documentElement.classList.contains("wide"); }
/* the tile size a declared column count implies at the reference
   width — or an explicit `tile_width`, which always wins */
function tileWidthOf(cols, declared) {
  const w = +declared;
  if (w > 0) return w;
  return (REF_W - GRID_PAD - (cols - 1) * GRID_GAP) / Math.max(1, cols);
}
/* the CONTENT width a grid has to fill — the viewport less padding,
   or the declared cap, whichever is smaller */
function usableWidth(maxW) {
  const vw = (window.innerWidth || REF_W) - GRID_PAD;
  return maxW > 0 ? Math.min(maxW, vw) : vw;
}
function colsFor(cols, declaredTileW, usable) {
  if (!isWide()) return cols;
  const tw = tileWidthOf(cols, declaredTileW);
  const u = usable || usableWidth(0);
  const n = Math.floor((u + GRID_GAP) / (tw + GRID_GAP));
  return Math.max(cols, Math.min(n, MAX_COLS));
}
/* SPAN IS A PROPORTION, NOT A COUNT (v0.68). `span: 2` was authored in
   a 2-column world, where it plainly meant "the whole row" — 39 tiles
   in the live config say so. Read literally at 5 columns it would mean
   "two fifths", which nobody wrote. So a span scales: span N of a
   declared C covers the same FRACTION of the real count, and N >= C
   means full width at any size. span 1 is never scaled — an ordinary
   tile is one column everywhere. */
function spanOf(t, declaredCols, actualCols) {
  const n = +t.span;
  if (!(n >= 2)) return 1;
  if (!isWide() || actualCols === declaredCols) return Math.min(n, actualCols);
  if (n >= declaredCols) return actualCols;              /* was full width */
  return Math.max(2, Math.min(actualCols,
    Math.round(n / declaredCols * actualCols)));
}
function makeTile(t, row, spanCols) {
  const el = document.createElement("div");
  const sp = spanCols || 1;
  /* IDENTITY (identity-palette V1, 2026-09-01): `identity` names a
     SLOT — the colour lives in the theme, never the config. A
     legacy/custom hex (`color`) stays honored, second-class: its
     badge is the hex and its wash derives from the hex. The style
     is additive, like a variant: icon-basic (silent default),
     icon-tint, icon-bloom for activities; text, text-bloom for
     presets. */
  const acc0 = t.accent != null ? t.accent : t.identity;
  const idt = typeof acc0 === "string" && ID_SLOTS[acc0] ? acc0 : null;
  const as0 = t.accent_style != null ? t.accent_style : t.identity_style;
  const ids = typeof as0 === "string" ? ID_STYLES[as0] : null;
  el.className = "tile wgt-" + t.type + (row ? " row" : "") + (!row && sp === 2 ? " span2" : "") +
    (idt || t.color ? " tacc" : "") + (idt ? " idt id-" + idt : "") +
    (ids ? " " + ids : "") + (t.brw ? " brw" : "") +
    /* chassis-level class passthrough (v0.68.1): a generator that needs
       one specific look — the search "Searching…" line — says so once
       instead of earning a widget type */
    (typeof t.cls === "string" && /^[\w -]+$/.test(t.cls) ? " " + t.cls : "");
  /* .span2 carries the common case in CSS so compact output is
     unchanged; any other width is stated inline */
  if (!row && sp > 2) el.style.gridColumn = "span " + sp;
  /* PER-TILE HEIGHT (v0.84.7 — forum request: "on the Watch TV
     controller pages I'd like to have a nearly full screen
     visualization with artwork for what's currently playing but I
     don't see a way to adjust just that card's height"). `span` said
     how WIDE a tile is; nothing said how TALL — height was a
     per-SCREEN knob (grid.tile_h / row_h), so one big Now Playing card
     beside normal ones was literally unsayable. `h` states it for THIS
     tile: a number = px, or a css length ("40vh", "12rem"). The
     per-screen knobs still carry every tile that stays silent. */
  var th = t.h;
  if (th != null && th !== "") {
    var hv = typeof th === "number" || /^\d+$/.test(String(th))
      ? parseInt(th, 10) + "px" : String(th);
    if (/^[\d.]+(px|vh|vw|rem|em|%)$/.test(hv)) {
      el.style.height = hv;
      el.style.minHeight = hv;   /* an explicit h beats a widget's min-height
                                    (the photo card's 132px floor, v0.85.7) */
      el.style.setProperty("--tile-h", hv);   /* row-mode + inner sizing */
    }
  }
  el.id = "tile_" + t.id;
  /* per-tile accent (v0.48.3): the activity's ACCENT paints its icon
     circle — see grid.css .tacc. A slot resolves through CSS
     (.id-<slot> maps --tacc/--idw to the theme tokens); only the
     second-class custom hex is set inline, its wash triplet parsed
     here so rgba(var(--idw), a) still composes. */
  if (!idt && t.color) {
    el.style.setProperty("--tacc", t.color);
    const tri = hexTriplet(t.color);
    if (tri) el.style.setProperty("--idw", tri);
    /* V2 ink: the same WCAG measurement the generator bakes for
       slots, run here for the second-class custom hex */
    const ink = pickInk(t.color);
    if (ink) el.style.setProperty("--tink", ink);
  }
  /* PER-TILE CSS VARIABLES (v0.85.7 — Suresh: "In advanced (JSON) how
     would I change font size and weight? And is it possible to use
     drop shadows?"). t.css_vars is a plain map of custom properties
     set on THIS tile's element — the same mechanism the remote
     profile's `style` uses, scoped to one card. Because the tile CSS
     already reads its numbers through variables, overriding the
     variable here restyles just this tile:
       "--fs-1": "18px"      label font size
       "--fw-1": "700"       label font weight
       "--tile-shadow": "0 4px 14px rgba(0,0,0,.45)"   card drop shadow
       "--lbl-shadow": "0 1px 3px rgba(0,0,0,.8)"      label text shadow
     Only --names are accepted; values with ; or } are refused. */
  /* LABEL POSITION (v0.85.7 — Suresh: "I could swear we used to have
     a label location parameter"): we never did — now we do. Rides as
     a class; today the photo nav card's overlay CSS consumes it
     (bottom-left stays the default), other overlay widgets can join. */
  if (t.label_pos && /^(top|center|bottom)(-(left|center|right))?$/.test(String(t.label_pos)))
    el.classList.add("lp-" + t.label_pos);
  /* image_opacity (v0.85.7 on nav cards, chassis-level v0.85.8 now
     that photo presets share the dress): how much of the photo shows
     over the dark card. Absent = the stylesheet's .85 default. Only
     .roomimg reads --img-op, so setting it on a photo-less tile is
     inert. */
  if (t.image_opacity != null && isFinite(+t.image_opacity))
    el.style.setProperty("--img-op",
      String(Math.max(0, Math.min(1, +t.image_opacity))));
  if (t.css_vars && typeof t.css_vars === "object")
    for (var vk in t.css_vars) {
      var vv = String(t.css_vars[vk]);
      if (vk.indexOf("--") === 0 && vv.indexOf(";") < 0 && vv.indexOf("}") < 0)
        el.style.setProperty(vk, vv);
    }
  const w = WIDGETS[t.type] || {};
  const extra = w.body ? w.body(t) : `<div class="meter hidden"><i></i></div>`;
  const body = `<div class="lbl">${t.label}</div>
    <div class="sub"></div>${extra}<div class="hint"></div>`;
  /* inline sub: value rides the title line (right-aligned) instead of
     burning a second line — widgets opt in via inlineSub (bool or fn) */
  const inline = !row && (w.inlineSub === true ||
    (typeof w.inlineSub === "function" && w.inlineSub(t)));
  el.innerHTML = row
    ? iconHtml(t, true) + `<div class="txt">${body}</div>`
    : `<div class="top">${iconHtml(t, false)}<span class="lbl">${t.label}</span>${
        inline ? '<span class="sub subin"></span>' : ""}</div>
       ${inline ? "" : '<div class="sub"></div>'}${extra}<div class="hint"></div>`;
  /* CORNER BADGE (v0.62): a tiny mark naming what a tile IS, for grids
     that MIX kinds — the browse "All" view sets it, and nothing else
     does yet. Chassis level, so any tile may declare one. */
  if (typeof t.badge === "string" && t.badge.startsWith("material:")) {
    const bd = document.createElement("span");
    bd.className = "bdg material-symbols-outlined";
    bd.textContent = t.badge.slice(9);
    el.appendChild(bd);
  }
  /* ROUTING MARK (v0.70 — design-library-ui.md §5): a tiny amber
     hand-off glyph. This tile plays by EVICTING the cast player's
     queue; the mark is the visible half of the rule whose other half
     is the two-press confirm. Chassis-level like the badge; browse
     fallback results are the only setter today. */
  if (typeof t.mark === "string" && t.mark.startsWith("material:")) {
    const mk = document.createElement("span");
    mk.className = "mrk material-symbols-outlined";
    mk.textContent = t.mark.slice(9);
    el.appendChild(mk);
  }
  /* PROVENANCE, SPLIT (v0.73.2 — Suresh: "split this into two
     badges"): `src` = the SYSTEM that owns the id (SO/MA/HA, a
     two-letter mini badge, bottom-right); `svc` = the SERVICE the
     content came from (deezer/spotify/…, top-right, sliding inboard
     of a trailing ▶ when one occupies the corner). Chassis-level
     like the kind badge and the routing mark. */
  if (typeof t.src === "string" && /^[a-z]{1,3}$/.test(t.src)) {
    const sb = document.createElement("span");
    sb.className = "srcb";
    sb.textContent = t.src;
    el.appendChild(sb);
  }
  if (typeof t.svc === "string" && /^[a-z0-9]{1,10}$/.test(t.svc)) {
    const sv = document.createElement("span");
    sv.className = "svcb";
    sv.textContent = t.svc;
    el.appendChild(sv);
    /* the service also rides as a CLASS (v0.85.7): the library's art
       tiles draw it as a colored dot, the list rows as a colored
       left bar — see grid.css .svc-spotify etc. */
    el.classList.add("svc-" + t.svc);
  }
  el.addEventListener("click", () => {
    if (el._heldFired) { el._heldFired = false; return; }
    setFocus(t.id); act("select");
  });
  /* touch LONG-PRESS: widgets that declare hold() get a 550ms pointer
     timer (a TOUCH gesture on the panel — the physical-remote hold
     doctrine, KeyMapper-owned, is untouched) */
  if (w.hold) {
    let hT = null, hX = 0, hY = 0;
    const clear = () => { if (hT) { clearTimeout(hT); hT = null; } };
    el.addEventListener("pointerdown", ev => {
      hX = ev.clientX; hY = ev.clientY; el._heldFired = false;
      clear();
      hT = setTimeout(() => { hT = null; el._heldFired = true; w.hold(t.entity, t); }, 550);
    });
    el.addEventListener("pointermove", ev => {
      if (hT && Math.hypot(ev.clientX - hX, ev.clientY - hY) > 12) clear();
    });
    el.addEventListener("pointerup", clear);
    el.addEventListener("pointercancel", clear);
    el.addEventListener("pointerleave", clear);
  }
  if (w.wire) w.wire(el, t);
  /* trailing action slot: chassis-level, any tile may declare one.
     Device tiles (detailable widgets whose entity has a detail
     generator) get an implicit settings trail → detail screen;
     set trailing: false in config to suppress it. */
  const trailing = trailingOf(t);
  if (trailing) {
    /* PROMINENCE IS DECLARED (v0.68.1 — Suresh, of the library button
       on Now Playing: "Lets try inverting the library launch button,
       to make it more prominent. And give it just a little more
       width."). A trail is a chassis slot used by every device tile's
       quiet ⚙ chevron, so inverting THE class would shout everywhere.
       `trailing.emphasis: "accent"` says which one earns it. */
    const acc = trailing.emphasis === "accent";
    el.classList.add("has-trail");
    if (acc) el.classList.add("has-trail-acc");
    const tr = document.createElement("button");
    tr.className = "trail" + (acc ? " tracc" : "");
    tr.dataset.fid = t.id + TRAIL;
    tr.innerHTML = iconHtml({ icon: trailing.icon || "material:chevron_right" }, false);
    tr.addEventListener("click", ev => {
      ev.stopPropagation();
      /* the parent tile is the confirm cue for a routed play (v0.70.1) */
      runAction(trailing.action, el);
    });
    el.appendChild(tr);
  }
  return el;
}

