/* OWNERSHIP (v0.85.7 — the grown-up strategy, Suresh: "bucket every
   part into (a) stock [repo always wins] (b) variant [repo and user
   might fight] (c) user [user always wins]").

   Everything in an install belongs to exactly one bucket, and the
   fights all live in (b). This module is the referee for (b): it
   decides, by CONTENT FINGERPRINT, whether an instance's copy of a
   stock unit is still ours (any shape we ever shipped → the repo may
   refresh it) or has been edited (→ it is the user's, formally and
   forever). The full bucket inventory lives in
   docs/design-ownership-buckets.md.

   THE RULE, in one line: a stock-id unit whose fingerprint matches
   ANY shape we ever shipped (or ever produced by healing a shipped
   shape) is pristine and heals silently; anything else under a stock
   id is a pre-lock edit and gets LEGITIMIZED — stamped variant_of so
   it is officially the user's fork (unlocked in the Studio, never
   healed again) with a forked_by_update note so the Studio can say
   what happened and offer "Reset to built-in".

   FAILURE DIRECTION, by design: an unknown-but-actually-pristine
   shape (some intermediate heal state we failed to enumerate) is
   classified "edited" → the user keeps a working copy and gets a
   notice + one-tap reset. Never data loss, never silent stranding.
   The reverse mistake would need a sha1 collision.

   The fingerprint history itself is studio-src/src/lib/stock-history.js,
   GENERATED by tools/gen-stock-history.mjs from every tagged
   starter-config.json — never hand-edited. */

/* ---- stable stringify: sorted keys, compact, deterministic ---- */
export function stableStringify(v) {
  if (v === null || typeof v !== "object") return JSON.stringify(v);
  if (Array.isArray(v)) return "[" + v.map(stableStringify).join(",") + "]";
  const keys = Object.keys(v).sort();
  return "{" + keys.map(k => JSON.stringify(k) + ":" + stableStringify(v[k]))
    .join(",") + "}";
}

/* ---- sha1, pure JS, synchronous (crypto.subtle is async and the
   heal chain is sync; input is ASCII JSON so charCodeAt is safe) ---- */
export function sha1hex(str) {
  const rotl = (n, s) => ((n << s) | (n >>> (32 - s))) >>> 0;
  const bytes = [];
  for (let i = 0; i < str.length; i++) {
    const c = str.charCodeAt(i);
    if (c < 128) bytes.push(c);
    else if (c < 2048) bytes.push(192 | (c >> 6), 128 | (c & 63));
    else bytes.push(224 | (c >> 12), 128 | ((c >> 6) & 63), 128 | (c & 63));
  }
  const ml = bytes.length * 8;
  bytes.push(128);
  while (bytes.length % 64 !== 56) bytes.push(0);
  for (let i = 7; i >= 0; i--) bytes.push((ml / Math.pow(2, i * 8)) & 255);
  let h0 = 0x67452301, h1 = 0xEFCDAB89, h2 = 0x98BADCFE,
      h3 = 0x10325476, h4 = 0xC3D2E1F0;
  const w = new Array(80);
  for (let i = 0; i < bytes.length; i += 64) {
    for (let j = 0; j < 16; j++)
      w[j] = ((bytes[i + j * 4] << 24) | (bytes[i + j * 4 + 1] << 16) |
              (bytes[i + j * 4 + 2] << 8) | bytes[i + j * 4 + 3]) >>> 0;
    for (let j = 16; j < 80; j++)
      w[j] = rotl(w[j - 3] ^ w[j - 8] ^ w[j - 14] ^ w[j - 16], 1);
    let a = h0, b = h1, c = h2, d = h3, e = h4;
    for (let j = 0; j < 80; j++) {
      let f, k;
      if (j < 20)      { f = (b & c) | (~b & d);          k = 0x5A827999; }
      else if (j < 40) { f = b ^ c ^ d;                   k = 0x6ED9EBA1; }
      else if (j < 60) { f = (b & c) | (b & d) | (c & d); k = 0x8F1BBCDC; }
      else             { f = b ^ c ^ d;                   k = 0xCA62C1D6; }
      const t = (rotl(a, 5) + f + e + k + w[j]) >>> 0;
      e = d; d = c; c = rotl(b, 30); b = a; a = t;
    }
    h0 = (h0 + a) >>> 0; h1 = (h1 + b) >>> 0; h2 = (h2 + c) >>> 0;
    h3 = (h3 + d) >>> 0; h4 = (h4 + e) >>> 0;
  }
  return [h0, h1, h2, h3, h4]
    .map(x => ("00000000" + x.toString(16)).slice(-8)).join("");
}

/* ---- normalization: what a fingerprint deliberately IGNORES ----

   VOLATILE_KEYS are bookkeeping, not content: two copies that differ
   only here are the same unit.

   SAFE-DRIFT normalizers are "the registry of safe slipstream keys":
   every key our OWN heal code has ever added, removed or rewritten on
   stock copies. A pristine config can sit at any intermediate heal
   level, so these keys must never make it look edited. Each entry
   names the heal that motivated it — extend this list whenever a new
   surgical heal ships, or that heal's output will misread as a user
   edit (harmless but noisy: legitimize instead of silent heal). */
export const VOLATILE_KEYS = ["gen", "parent", "variant_of", "forked_by_update"];

function normalizeTiles(tiles) {
  const out = [];
  for (const t of tiles || []) {
    if (!t || typeof t !== "object") { out.push(t); continue; }
    if (t.id === "mq_pull") continue;              // v0.51: heal-removed
    const c = Object.assign({}, t);
    if (c.type === "media") {
      delete c.style;                              // v0.85.0 bug: heal-stripped
      delete c.np_default;                         // v0.85.x: heal-added
    }
    out.push(c);
  }
  return out;
}

export function normalizeController(u) {
  const c = JSON.parse(JSON.stringify(u || {}));
  for (const k of VOLATILE_KEYS) delete c[k];
  delete c.font_scope;                             // v0.52.1: heal-added
  delete c.banner;                                 // v0.50.2: heal-removed
  delete c.context;                                // v0.48.2: heal-stripped (purity)
  if (c.tiles) c.tiles = normalizeTiles(c.tiles);
  for (const sec of c.sections || [])
    if (sec.tiles) sec.tiles = normalizeTiles(sec.tiles);
  return c;
}

/* generic unit (keymaps, dialect sub-objects): volatile keys only */
export function normalizeUnit(u) {
  const c = JSON.parse(JSON.stringify(u || {}));
  for (const k of VOLATILE_KEYS) delete c[k];
  return c;
}

export function controllerFp(u) {
  return sha1hex(stableStringify(normalizeController(u))).slice(0, 12);
}
export function unitFp(u) {
  return sha1hex(stableStringify(normalizeUnit(u))).slice(0, 12);
}

/* ---- classification ----
   instance: the config's copy. stock: the current shipped shape.
   history: array of fingerprints of every shape we ever shipped for
   this unit id (current one included by the generator). */
export function classifyController(instance, stock, history) {
  if (!instance) return "absent";
  if (instance.variant_of) return "fork";          // bucket (c), formally
  const fp = controllerFp(instance);
  if (fp === controllerFp(stock)) return "current";
  if ((history || []).indexOf(fp) >= 0) return "pristine";
  return "edited";                                 // bucket (b): the fight
}

/* ---- the referee: heal one stock controller id in place ----
   Returns what it did: "kept" | "healed" | "legitimized". */
export function refereeController(cfg, cid, stock, history, extra) {
  const c = cfg.controllers[cid];
  const verdict = classifyController(c, stock, history);
  if (verdict === "absent" || verdict === "fork") return "kept";
  if (verdict === "current" || verdict === "pristine") {
    if (verdict === "current" && (c.gen || 0) === (stock.gen || 0))
      return "kept";                               // truly nothing to do
    const fresh = JSON.parse(JSON.stringify(stock));
    if (c.parent) fresh.parent = c.parent;         // protected key: content graph
    Object.assign(fresh, extra || {});
    cfg.controllers[cid] = fresh;
    return "healed";                               // repo wins — it was ours
  }
  /* edited in place (pre-lock era). The user wins: this copy becomes
     their fork, formally — unlocked in the Studio, never healed again,
     with a note so the Studio can explain and offer Reset. */
  c.variant_of = cid;
  c.forked_by_update = { from_gen: c.gen || 0, stock_gen: stock.gen || 0 };
  delete c.gen;                                    // a fork carries no stock gen
  return "legitimized";
}
