/* GENERATED by tools/gen-stock-history.mjs — do not hand-edit.
   Fingerprints of every stock shape ever shipped (tagged starters +
   current stocklib), consumed by ownership.js via stocklib's healers.
   Snapshots: starter-v0.83.10.json, starter-v0.83.5.json, starter-v0.83.6.json, starter-v0.83.7.json, starter-v0.83.8.json, starter-v0.83.9.json, starter-v0.84.1.json, starter-v0.85.3.json, starter-v0.85.7.json */
export default {
 "controllers": {
  "music": [
   "41c13130a71d",
   "b3cc1bd486c4",
   "dbdb85e9f658"
  ],
  "apps": [
   "c72235765d39",
   "60518084345a"
  ],
  "music_library": [
   "c12d797cbda5"
  ],
  "tv": [
   "78dbfe5da550",
   "1e1983347676"
  ],
  "climate": [
   "2d62ab684453"
  ],
  "light": [
   "57867a76c599"
  ],
  "cover": [
   "f9555e05c293"
  ],
  "fan": [
   "2fe1127602f5"
  ],
  "switch": [
   "f29b6aa1dc17"
  ],
  "media": [
   "a7f15a534e3f"
  ]
 },
 "remoteKeymaps": {
  "astrion": [
   "0effec037d5b",
   "29c62b1d1eff",
   "2cc7d4d52ba4",
   "e95d4d8ee95c"
  ],
  "astrion2": [
   "b73b7d0be09c",
   "5522b1f5906d",
   "d878f1e41ca4"
  ],
  "rs90": [
   "0a45885480b3",
   "47c8d9d78c37",
   "999e7bee53d4"
  ]
 },
 "dialects": {
  "firetv": [
   "71a4b903862d",
   "ba11a1e221b8",
   "5408dda7c825",
   "0b124fc02879"
  ],
  "tizen": [
   "b962c6033f86"
  ],
  "googletv": [
   "e828fb6d39d8",
   "74167b7f578c"
  ],
  "appletv": [
   "4aa335fc67a0"
  ]
 },
 "dialectDpad": {
  "appletv": [
   "6aa063ff95bd"
  ]
 },
 "inputPolicy": {
  "physical_buttons": [
   "7e60077378db",
   "b1ec19b97c69"
  ]
 }
};
