"""Layered catalogs — the spread model (v0.86.0).

The effective catalog is the stock catalog with the user's catalog
spread over it: ``effective = {**stock, **user}``. Stock never enters
the user's config; the user layer stores only additions, forks, and
tombstones (a key set to null = "hide the stock entry"). Ownership is
positional: if a key is in the user layer, it is the user's, by
definition. Full spec: docs/design-layered-catalogs.md.

Scope (0.86.0): the ``apps`` master list and ``dialects``. The merge
grain, per the spec's rulings:
  - apps: per entry;
  - dialects: two-level — the dialect map merges per dialect id, and
    inside a stock dialect the ``apps``/``keys`` sub-catalogs merge
    per entry while every other field (name, wake, dpad_commands,
    channels, forbidden, capabilities, ...) merges per FIELD — the
    blessed exception, so one wake_delay tweak cannot freeze a
    platform's catalog;
  - tombstones are ``None`` in place, dropped after the spread.

The merge lives HERE, at the integration store: the engine reads the
deployed effective config and never changes; the Studio reads the
effective config and computes provenance against its own stocklib;
and every write funnels through subtract_config() so nothing can ever
bake stock into the user layer (the never-write-merged contract).

The one-shot lift-out migration classifies each pre-layers entry by
CONTENT FINGERPRINT against catalog-history.json (generated by
tools/gen-stock-history.mjs from every tagged starter + the current
stock): any shape we ever shipped lifts out (stock supplies it),
anything else stays as the user's fork, and a stock key missing from
a config is a tombstone ONLY if every shipped generation carried it —
a key younger than the user's seed simply starts flowing.

Pure functions + one cached file read; no HA imports."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

# bookkeeping keys the JS referee strips before fingerprinting
# (ownership.js VOLATILE_KEYS) — kept identical so the two sides can
# never disagree about what a shape IS
VOLATILE_KEYS = ("gen", "parent", "variant_of", "forked_by_update")

# dialect sub-catalogs that merge per entry; every other dialect key
# merges per field
DIALECT_SUBCATS = ("apps", "keys")

# the history marker meaning "some shipped generation lacked this key"
ABSENT = "__absent__"


# ---- fingerprints (parity with studio-src/src/lib/ownership.js) ----

def stable_stringify(v) -> str:
    """Sorted keys, compact, deterministic — byte-identical to the JS
    stableStringify for the JSON-shaped values catalogs hold."""
    if v is None or not isinstance(v, (dict, list)):
        return json.dumps(v, ensure_ascii=False, separators=(",", ":"))
    if isinstance(v, list):
        return "[" + ",".join(stable_stringify(x) for x in v) + "]"
    return "{" + ",".join(
        json.dumps(k, ensure_ascii=False) + ":" + stable_stringify(v[k])
        for k in sorted(v)) + "}"


def unit_fp(u) -> str:
    """sha1[:12] of the normalized shape — ownership.js unitFp."""
    if isinstance(u, dict):
        u = {k: v for k, v in u.items() if k not in VOLATILE_KEYS}
    return hashlib.sha1(
        stable_stringify(u).encode("utf-8")).hexdigest()[:12]


# ---- the stock layer ------------------------------------------------

_STOCK_CACHE: dict = {}


def stock_catalogs(component_dir: Path) -> dict:
    """The shipped catalogs — read once from the bundled
    starter-config.json (the same artifact the stock-history tooling
    snapshots, so there is exactly one source of truth)."""
    key = str(component_dir)
    if key not in _STOCK_CACHE:
        starter = json.loads(
            (component_dir / "starter-config.json").read_text("utf-8"))
        _STOCK_CACHE[key] = {
            "apps": starter.get("apps") or {},
            "dialects": starter.get("dialects") or {},
        }
    return _STOCK_CACHE[key]


def load_catalog_history(component_dir: Path) -> dict:
    """The per-entry fingerprint registry (generated; see module doc).
    Missing file → empty history: lift-out then only lifts entries
    matching CURRENT stock, which is safe (fewer lifts, never a lost
    edit)."""
    path = component_dir / "catalog-history.json"
    try:
        return json.loads(path.read_text("utf-8"))
    except (OSError, ValueError):
        return {}


# ---- the spread -----------------------------------------------------

def _spread(stock: dict, user: dict) -> dict:
    """Per-entry spread with null tombstones dropped; stock order
    first, user additions after, forks keep their stock position."""
    out = {}
    for k, v in (stock or {}).items():
        if user is not None and k in user:
            if user[k] is not None:
                out[k] = user[k]
            # None → tombstone: the key is dropped
        else:
            out[k] = v
    for k, v in (user or {}).items():
        if k not in (stock or {}) and v is not None:
            out[k] = v
    return out


def _merge_dialect(stock_d: dict, user_d: dict) -> dict:
    """Two-level dialect merge: sub-catalogs per entry, scalars per
    field (None field = tombstone for that field)."""
    out = {}
    keys = list(stock_d.keys()) + [k for k in user_d if k not in stock_d]
    for k in keys:
        in_user = k in user_d
        if k in DIALECT_SUBCATS:
            sub = _spread(stock_d.get(k) or {},
                          user_d.get(k) if in_user else None)
            if sub:
                out[k] = sub
        elif in_user:
            if user_d[k] is not None:
                out[k] = user_d[k]
        else:
            out[k] = stock_d[k]
    return out


def merge_catalogs(stock: dict, user_apps, user_dialects) -> tuple:
    """(effective_apps, effective_dialects). A user catalog of None
    means the config never had the key — stock flows whole."""
    apps = _spread(stock["apps"], user_apps)
    dialects = {}
    s_dial = stock["dialects"]
    u_dial = user_dialects or {}
    for did in list(s_dial.keys()) + [d for d in u_dial if d not in s_dial]:
        if did in s_dial and did in u_dial:
            if u_dial[did] is None:
                continue                       # whole-dialect tombstone
            dialects[did] = _merge_dialect(s_dial[did], u_dial[did])
        elif did in u_dial:
            if u_dial[did] is not None:
                dialects[did] = u_dial[did]    # user's own dialect
        else:
            dialects[did] = s_dial[did]
    return apps, dialects


def merge_config(stock: dict, cfg: dict) -> dict:
    """A workspace config with its catalogs made effective. Shallow
    copy — every non-catalog key is shared, untouched."""
    if not isinstance(cfg, dict):
        return cfg
    out = dict(cfg)
    # legacy spelling: some configs carry app_classes instead of dialects
    dial_key = "dialects" if "dialects" in cfg or "app_classes" not in cfg \
        else "app_classes"
    apps, dialects = merge_catalogs(
        stock, cfg.get("apps"), cfg.get(dial_key))
    out["apps"] = apps
    out[dial_key] = dialects
    return out


# ---- the subtraction (the never-write-merged contract) --------------

def _subtract(stock: dict, effective: dict) -> dict:
    """The user layer an effective catalog implies: equal entries are
    omitted (stock supplies them), different or new entries are kept,
    stock keys missing from the effective catalog become tombstones."""
    out = {}
    stock = stock or {}
    effective = effective or {}
    for k, v in effective.items():
        if k in stock and unit_fp(v) == unit_fp(stock[k]):
            continue
        out[k] = v
    for k in stock:
        if k not in effective:
            out[k] = None
    return out


def _subtract_dialect(stock_d: dict, eff_d: dict) -> dict:
    out = {}
    for k, v in eff_d.items():
        if k in DIALECT_SUBCATS:
            sub = _subtract(stock_d.get(k) or {}, v)
            if sub:
                out[k] = sub
        elif k in stock_d:
            if unit_fp(v) != unit_fp(stock_d[k]):
                out[k] = v
        else:
            out[k] = v
    for k in stock_d:
        if k in eff_d:
            continue
        if k in DIALECT_SUBCATS:
            sub = _subtract(stock_d[k], {})
            if sub:
                out[k] = sub
        else:
            out[k] = None
    return out


def subtract_config(stock: dict, cfg: dict) -> dict:
    """An EFFECTIVE workspace config reduced to its user layer for the
    catalogs; everything else passes through untouched.

    CONTRACT: call this only at the write boundaries, on configs that
    are effective-shaped — the Studio's POST body, a restored backup,
    a reseed result, a first-run seed. The input's catalogs are read
    as "what the user wants to SEE": an entry equal to stock is
    omitted (stock supplies it), a different or new entry is kept, a
    stock key MISSING from a present catalog is a deliberate deletion
    and becomes a tombstone. A catalog key absent entirely makes no
    statement — it stays absent and stock flows whole. Because the
    store holds deltas, this must NEVER run on a stored layer (it
    would read the omissions as deletions); merge_config() is the
    inverse that makes a stored layer effective again."""
    if not isinstance(cfg, dict):
        return cfg
    out = dict(cfg)
    dial_key = "dialects" if "dialects" in cfg or "app_classes" not in cfg \
        else "app_classes"
    if isinstance(cfg.get("apps"), dict):
        apps = _subtract(stock["apps"], cfg["apps"])
        if apps:
            out["apps"] = apps
        else:
            out.pop("apps", None)
    if isinstance(cfg.get(dial_key), dict):
        eff_dial = cfg[dial_key]
        dialects = {}
        s_dial = stock["dialects"]
        for did, d in eff_dial.items():
            if did in s_dial and isinstance(d, dict):
                sub = _subtract_dialect(s_dial[did], d)
                if sub:
                    dialects[did] = sub
            else:
                dialects[did] = d
        for did in s_dial:
            if did not in eff_dial:
                dialects[did] = None
        if dialects:
            out[dial_key] = dialects
        else:
            out.pop(dial_key, None)
    return out


# ---- the one-shot lift-out migration --------------------------------

def _shipped(history_list, value) -> bool:
    return bool(history_list) and unit_fp(value) in history_list


def _absence_shipped(history_list) -> bool:
    """True when some shipped generation lacked this key — a config
    missing it is merely older than the key, not a curated deletion."""
    return not history_list or ABSENT in history_list


def lift_out(stock: dict, history: dict, cfg: dict) -> tuple:
    """(new_cfg, report). Classify every catalog entry of a
    pre-layers config: shipped shape → lift (stock supplies it);
    edited shape → keep (the user's fork); stock key absent from the
    config → tombstone only when every shipped generation carried it.
    A config with no catalogs at all is returned unchanged — stock
    flows whole and nothing needs saying.

    RUN-ONCE, BY THE STAMP: this reads its input as a PRE-LAYERS
    config (full seeded catalogs). Re-running it on a partial user
    layer would read lifted-out entries as deletions and tombstone
    them — which is why the migration saves the catalog_layers stamp
    and its whole pass is all-or-nothing (an exception saves nothing,
    so the retry always starts from unchanged data)."""
    if not isinstance(cfg, dict):
        return cfg, []
    report = []
    out = dict(cfg)
    h_apps = history.get("apps") or {}
    h_dapps = history.get("dialect_apps") or {}
    h_dkeys = history.get("dialect_keys") or {}
    h_dfields = history.get("dialect_fields") or {}

    def lift_map(user_map, stock_map, hist, label):
        res = {}
        for k, v in user_map.items():
            hl = hist.get(k) or []
            if k in stock_map and (_shipped(hl, v)
                                   or unit_fp(v) == unit_fp(stock_map[k])):
                report.append("lift %s.%s" % (label, k))
            else:
                res[k] = v
                if k in stock_map:
                    report.append("fork %s.%s" % (label, k))
        for k in stock_map:
            if k not in user_map and not _absence_shipped(hist.get(k) or []):
                res[k] = None
                report.append("tombstone %s.%s" % (label, k))
        return res

    if isinstance(cfg.get("apps"), dict):
        apps = lift_map(cfg["apps"], stock["apps"], h_apps, "apps")
        if apps:
            out["apps"] = apps
        else:
            out.pop("apps", None)

    dial_key = "dialects" if "dialects" in cfg else (
        "app_classes" if "app_classes" in cfg else None)
    if dial_key and isinstance(cfg.get(dial_key), dict):
        dialects = {}
        s_dial = stock["dialects"]
        for did, d in cfg[dial_key].items():
            if did not in s_dial or not isinstance(d, dict):
                dialects[did] = d          # the user's own dialect
                continue
            res = {}
            for k, v in d.items():
                if k in DIALECT_SUBCATS:
                    hist = (h_dapps if k == "apps" else h_dkeys).get(did) or {}
                    sub = lift_map(v or {}, s_dial[did].get(k) or {}, hist,
                                   "%s.%s.%s" % (dial_key, did, k))
                    if sub:
                        res[k] = sub
                else:
                    hl = (h_dfields.get(did) or {}).get(k) or []
                    if k in s_dial[did] and (_shipped(hl, v)
                            or unit_fp(v) == unit_fp(s_dial[did][k])):
                        report.append("lift %s.%s.%s" % (dial_key, did, k))
                    else:
                        res[k] = v
                        if k in s_dial[did]:
                            report.append("fork %s.%s.%s" % (dial_key, did, k))
            # fields the stock dialect has that the config lacks:
            # tombstone only when every shipped generation carried them
            for k in s_dial[did]:
                if k in d or k in DIALECT_SUBCATS:
                    continue
                if not _absence_shipped((h_dfields.get(did) or {}).get(k) or []):
                    res[k] = None
                    report.append("tombstone %s.%s.%s" % (dial_key, did, k))
            if res:
                dialects[did] = res
        # stock dialects missing entirely from the config
        for did in s_dial:
            if did not in cfg[dial_key] and not _absence_shipped(
                    (history.get("dialects_presence") or {}).get(did) or []):
                dialects[did] = None
                report.append("tombstone %s.%s" % (dial_key, did))
        if dialects:
            out[dial_key] = dialects
        else:
            out.pop(dial_key, None)
    return out, report
